DROP TABLE PARTE_SELECCIONADA;
DROP TABLE MOTORES;
DROP TABLE USUARIOS_KDRON;
DROP TABLE ROLES;
DROP TABLE BATERIAS;
DROP TABLE HELICES;
DROP TABLE VARIADORES;


CREATE TABLE USUARIOS_KDRON
 (USUARIO_ID                   NUMBER(30),
  NOMBRE			   		   VARCHAR (50),
  APELLIDO 					   VARCHAR (50),
  EMAIL                        VARCHAR2(50),
  PASSWORD                     VARCHAR2(10),
  ROL_ID                       NUMBER(3))
TABLESPACE TS_KDRON;